Project.MVCUI/Controllers/BillController.cs
using Project.BLL.DeisgnPatterns.GenericRepository.ConRep;
using Project.Entities.Models;
using Project.MVCUI.ModelVM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.MVCUI.Controllers
{
    public class BillController : Controller
    {
        ProductRepository _product;

        AppUserRepository _appUser;

        BillRepository _bill;

        UserBillRepository _userBill;

        public BillController()
        {
            _product = new ProductRepository();

            _appUser = new AppUserRepository();

            _bill = new BillRepository();

            _userBill = new UserBillRepository();
        }
        // GET: Bill
        public ActionResult BillAdd()
        {
            BillVM BVM = new BillVM()
            {
                Products = _product.GetActives(),
                AppUsers = _appUser.GetActives(),
            };

            return View(BVM);
        }

        [HttpPost]

        public ActionResult BillAdd(int user,int[] quantity,params string[] product)
        {
            Dictionary<int, int> productQuantities = new Dictionary<int, int>();

            int index = 0;

            for (int i = 0; i < quantity.Length ; i++)
            {
                int currentNumber = quantity[i];
                if(currentNumber != 0)
                {
                    productQuantities.Add(Convert.ToInt32(product[index]), currentNumber);
                    index++;

                }
            }

            Bill bill = new Bill()
            {
                AppUserID = user,
            };

            _bill.Add(bill);

            List<Product> products = new List<Product>();

            decimal totalPrice = 0;

            foreach (KeyValuePair<int,int> item in productQuantities)
            {
                products.Add(_product.Find(item.Key));
                _product.Find(item.Key).Quantity = item.Value;

               

            };

            foreach (Product item in products)
            {
                totalPrice += item.Price * item.Quantity;
            }

    


            UserBill userBill = new UserBill()
            {
                BillID = bill.ID,
                AppUserID = user,
                Products = products,
                TotalPrice = totalPrice,
                AppUser = _appUser.Find(user),
                

            };

            _userBill.Add(userBill);



            return RedirectToAction("BillList");
        }

        public ActionResult BillList()
        {
            BillVM BVM = new BillVM()
            {
                UserBills = _userBill.GetActives()
            };

            return View(BVM);
        }

        public ActionResult BillUpdate(int billID,int AppUserID)
        {
            UserBill userBill = _userBill.FirstOrDefault(x => x.BillID == billID && x.AppUserID == AppUserID);

            BillVM BVM = new BillVM()
            {
                userBill = userBill,
            };

            return View(BVM);
        }

        [HttpPost]

        public ActionResult BillUpdate(int billID,int user, int[] quantity, params string[] product)
        {
            Dictionary<int, int> productQuantities = new Dictionary<int, int>();

            int index = 0;

            for (int i = 0; i < quantity.Length; i++)
            {
                int currentNumber = quantity[i];
                if (currentNumber != 0)
                {
                    productQuantities.Add(Convert.ToInt32(product[index]), currentNumber);
                    index++;

                }
            }

           

            

            List<Product> products = new List<Product>();

            decimal totalPrice = 0;

            foreach (KeyValuePair<int, int> item in productQuantities)
            {
                products.Add(_product.Find(item.Key));
                _product.Find(item.Key).Quantity = item.Value;



            };

            foreach (Product item in products)
            {
                totalPrice += item.Price * item.Quantity;
            }




            UserBill userBill = new UserBill()
            {
                BillID = billID,
                AppUserID = user,
                Products = products,
                TotalPrice = totalPrice,
                AppUser = _appUser.Find(user),


            };

            _userBill.UpdateMany(userBill);


            return RedirectToAction("BillList");
        }

        public ActionResult BillDelete(int billID,int appUserID)
        {
            _userBill.Delete(_userBill.FirstOrDefault(x => x.BillID == billID && x.AppUserID == appUserID));


            return RedirectToAction("BillList");
        }

    }
}

Project.MVCUI/Views/Bill/BillAdd.cshtml
@model BillVM
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BillAdd</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    <header>
        <div class="bg-slate-900 max-w-full h-24">
            <div class="ml-2 flex flex-row pt-4">
                <img class="h-16 w-16" src="~/Images/61177330982724000a19b190.png" />
                <label class="text-3xl ml-1 mt-2 font-mono text-slate-400 ">Invoice Processing Company</label>
            </div>


        </div>
    </header>

    <section>
        @using (Html.BeginForm("BillAdd", "Bill", FormMethod.Post))
        {
            <label for="users">Choose a user:</label>
            <select name="user" id="user">

                @foreach (AppUser item in Model.AppUsers)
                {
<option value="@item.ID">@item.FirstName @item.LastName @item.EMail</option>
                }
                
               
            </select>

            <br />
            

            foreach (Product item in Model.Products)
            {
                <input type="checkbox" id="@item.ID" name="product" value="@item.ID">
                <label>@item.Name</label> <label>@item.Price</label>
                <input type="number" id="@item.Name" name="quantity" min="0"><br>

            }

            <div class="">
                <button class=" mt-4 bg-blue-700 hover:bg-blue-600 text-sky-50 font-bold  py-2 px-4 rounded focus:outline-none focus:shadow-outline" style="height:50px;width:200px">
                    Add Bill
                </button>

            </div>

        }


    </section>
</body>
</html>

Project.MVCUI/Views/Bill/BillList.cshtml
@model BillVM

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BillList</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        table, th, td {
            border: 1px solid white;
            border-collapse: collapse;
        }

        th, td {
            background-color: #96D4D4;
        }
    </style>
</head>
<body>
    <header>
        <div class="bg-slate-900 max-w-full h-24 flex flex-row">
            <div class="ml-2 flex flex-row pt-4">
                <img class="h-16 w-16" src="~/Images/61177330982724000a19b190.png" />
                <label class="text-3xl ml-1 mt-2 font-mono text-slate-400 ">Invoice Processing Company</label>
            </div>

            <a class="pt-8 ml-2 text-xl font-bold text-slate-300" href="/Product/ProductList">List Product</a>

            <a class="pt-8 ml-2 text-xl font-bold text-slate-300" href="/Home/AppUserList">List User</a>

            <a class="pt-8 ml-2 text-xl font-bold text-slate-300" href="/Bill/BillAdd">Bill Add</a>


        </div>
    </header>



    <section>
        <table class="table-fixed border-collapse border border-slate-500">
            <thead>
                <tr>
                    @{ 
                        int lenght = 0;
                    } 
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>E Mail</th>
                    <th colspan="@lenght">Products</th>
                    <th>Total Price</th>
                    <th colspan="2">Options</th>
                </tr>
            </thead>
            <tbody>
                @foreach (UserBill item in Model.UserBills)
                {
                    int index = 0;
                    <tr>
                        <td>@item.AppUser.FirstName</td>
                        <td>@item.AppUser.LastName</td>
                        <td>@item.AppUser.EMail</td>

                        @{
                            lenght = item.Products.Count;
                        }

                    <td>

                        <select>

                            
                            @foreach (Product myItem in item.Products)
                            {
                                <option>
                                    
                                  Name:@myItem.Name Quantity:@myItem.Quantity Price:@myItem.Price

                                </option>

                               


                            }
                            
                        </select>

                       

                    </td>

                            <td>@item.TotalPrice</td>

                            @index++;

                            <td class="text-amber-700 font-bold">@Html.ActionLink("Update", "BillUpdate", new { billID = item.BillID,appUserID = item.AppUserID })</td>
                            <td class="text-red-700 font-bold">@Html.ActionLink("Delete", "BillDelete", new { billID = item.BillID, appUserID = item.AppUserID })</td>
                        </tr>

                }
            </tbody>



        </table>
        <label class="text-xl text-amber-700">@TempData["info"]</label>
    </section>
</body>
</html>

Project.MVCUI/Views/Bill/BillUpdate.cshtml
@model BillVM
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BillUpdate</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    <header>
        <div class="bg-slate-900 max-w-full h-24">
            <div class="ml-2 flex flex-row pt-4">
                <img class="h-16 w-16" src="~/Images/61177330982724000a19b190.png" />
                <label class="text-3xl ml-1 mt-2 font-mono text-slate-400 ">Invoice Processing Company</label>
            </div>


        </div>
    </header>


    <section>
        @using (Html.BeginForm("BillUpdate", "Bill", FormMethod.Post))
        {
            foreach (Product item in Model.userBill.Products)
            {
                <input type="checkbox" checked="checked" id="@item.ID" name="product" value="@item.ID">
                <label>@item.Name</label> <label>@item.Price</label>
                <input value="@item.Quantity" type="number" id="@item.Name" name="quantity" min="0"><br>
                <input name="billID" type="hidden" value="@Model.userBill.BillID" />

            }

            <div class="">
                <button name="user" value="@Model.userBill.AppUser.ID" class=" mt-4 bg-blue-700 hover:bg-blue-600 text-sky-50 font-bold  py-2 px-4 rounded focus:outline-none focus:shadow-outline" style="height:50px;width:200px">
                    Update Bill
                </button>

            </div>

        }


    </section>
</body>
</html>